# namespace dev
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-bonus
  namespace: argocd
spec:
  project: default
  source:
    # gitlabで作成したリポジトリのURLに書き換える
    repoURL: 'http://gitlab.iot.com/gitlab-instance-fd210447/iot.git'
    path: simple_app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true