Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "yokawadaS" do |server|
    server.vm.hostname = "yokawadaS"
    server.vm.provider "virtualbox" do |v|
      v.name = "iot-server-p2"
    end
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/init.sh"
  end
end