Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.box = "ubuntu/focal64"

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.provider "virtualbox" do |v|
      v.name = "server"
    end
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | sh -
    SHELL
  end

  config.vm.define "agent" do |agent|
    agent.vm.hostname = "agent"
    agent.vm.provider "virtualbox" do |v|
      v.name = "agent"
    end
    agent.vm.network "private_network", ip: "192.168.56.111"
  end
end