Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.box = "ubuntu/focal64"

  config.vm.define "server" do |server|
    server.vm.hostname = "yokawadaS"
    server.vm.provider "virtualbox" do |v|
      v.name = "iot-server-p1"
    end
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface=enp0s8" sh -
      sudo chmod 644 /etc/rancher/k3s/k3s.yaml
      sudo cp -f /var/lib/rancher/k3s/server/node-token /vagrant/node-token
    SHELL
  end

  config.vm.define "agent" do |agent|
    agent.vm.hostname = "yokawadaSW"
    agent.vm.provider "virtualbox" do |v|
      v.name = "iot-agent-p1"
    end
    agent.vm.network "private_network", ip: "192.168.56.111"
    agent.vm.provision "shell", inline: <<-SHELL
      TOKEN=$(cat /vagrant/node-token)
      SERVER=https://192.168.56.110:6443
      curl -sfL https://get.k3s.io | K3S_URL=$SERVER K3S_TOKEN=$TOKEN INSTALL_K3S_EXEC="--flannel-iface=enp0s8" sh -
    SHELL
  end
end