grafana.ini:  
  server:  
    protocol: http  
    domain: localhost  
    root_url: "%(protocol)s://%(domain)s:3000/-/grafana"  
    serve_from_sub_path: true  
ingress:  
  enabled: true  
  hosts:  
    - "grafana.example.com"  
  path: "/-/grafana"  
service:  
  type: NodePort  
  nodePort: 32080